name: gelir_gider
description: Global-ready personal finance tracker (Flutter + Supabase).
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
<<<<<<< HEAD
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Core
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0

  # Supabase
  supabase_flutter: ^2.8.0

  # Local DB
  sqflite: ^2.3.3
  dependencies:
    collection: ^1.18.0
    cupertino_icons: ^1.0.8
    easy_localization: ^3.0.5
    excel: ^4.0.6
    fl_chart: ^1.1.1
  path_provider: ^2.1.4
  pdf: ^3.11.0
    flutter_riverpod: ^2.5.1
    go_router: ^16.2.5
    google_fonts: ^6.2.1
    google_sign_in: ^6.2.1
    home_widget: ^0.8.1
    http: ^1.2.2
    intl: ^0.20.2
    path: ^1.9.0
    path_provider: ^2.1.4
    pdf: ^3.11.0
    printing: ^5.13.4
    share_plus: ^12.0.0
    speech_to_text: ^7.3.0
    sqflite: ^2.3.3
    supabase_flutter: ^2.8.0
    uuid: ^4.4.2

  dev_dependencies:
    build_runner: ^2.4.12
    flutter_test:
      sdk: flutter
    json_serializable: ^6.8.0
    very_good_analysis: ^10.0.0
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  very_good_analysis: ^10.0.0
>>>>>>> d1f5fc0 (Readme.md)

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/sql/
