name: gelir_gider
description: Global-ready personal finance tracker (Flutter + Supabase).
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Core
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0

  # Supabase
  supabase_flutter: ^2.8.0

  # Local DB
  sqflite: ^2.3.3
  path_provider: ^2.1.4
  path: ^1.9.0

  # UI/UX
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  home_widget: ^0.5.1

  # Localization
  easy_localization: ^3.0.5

  # Voice input
  speech_to_text: ^6.6.2

  # Reports export
  pdf: ^3.11.0
  printing: ^5.13.4
  excel: ^2.1.2
  share_plus: ^10.0.2

  # Utils
  intl: ^0.19.0
  collection: ^1.18.0
  uuid: ^4.4.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/sql/
